spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak.iri-base.org/realms/iri}

spring.thymeleaf.cache: false

app:
  backend-url: ${BACKEND_URL:https://backend:11261}
