/*
 * Profit Basetool - squadron-management web app.
 * Copyright (C) 2026 Lucas Greuloch
 *
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.greluc.krt.profit.basetool.backend.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * One filled functional-rank position in the Profit-Bereich org chart (see Flyway migration {@code
 * V136}). A row binds a {@link User} to an {@link OrgChartPositionType} within one of the three
 * scopes (area leadership / Staffel / Spezialkommando) and, for the squadron sub-tree, to a {@link
 * #parent} position.
 *
 * <p><b>Scope discriminator.</b> A {@code null} {@link #orgUnit} marks an area-leadership position
 * (Bereichsleitung); a non-null {@link #orgUnit} marks a Staffel- or SK-scoped position. The {@code
 * chk_org_chart_scope} CHECK constraint keeps {@code position_type} and the nullability of {@code
 * org_unit_id} consistent at the database layer.
 *
 * <p><b>Tree.</b> {@link #parent} is only set for {@link OrgChartPositionType#DEPUTY_COMMAND_LEAD}
 * (points at its Kommandoleiter) and {@link OrgChartPositionType#ENSIGN} (points at a
 * Kommandoleiter; {@code null} means the Ensign reports directly to the Staffelleiter). The
 * self-referencing FK is {@code ON DELETE CASCADE}, so deleting a Kommandoleiter row removes its
 * Stv. and the Ensigns reporting into it in one statement; the inline editor warns the admin about
 * those children before the delete.
 *
 * <p><b>Kommando(gruppe).</b> A {@link OrgChartPositionType#COMMAND_LEAD} row models the Kommando
 * itself, not merely the person leading it: it carries an optional group {@link #name} and an
 * optional holder ({@link #user} may be {@code null} while the Kommandoleiter seat is still
 * vacant). This is the one rank allowed to have a null user — it lets an admin create and name a
 * Kommando, attach a Stv. Kommandoleiter and Ensigns to it, and only later assign the
 * Kommandoleiter. The {@code chk_org_chart_user} / {@code chk_org_chart_name} CHECK constraints
 * (migration {@code V138}) confine both the nullable holder and the {@code name} to this rank;
 * every other rank keeps its mandatory holder and a {@code null} name.
 *
 * <p><b>Descriptive only.</b> Nothing here feeds authorization — the chart records who holds which
 * functional rank; permissions stay with the role model and the {@code org_unit_membership} flags.
 */
@Entity
@Table(name = "org_chart_position")
@Getter
@Setter
@NoArgsConstructor
@ToString(callSuper = true)
public class OrgChartPosition extends AbstractEntity<UUID> {

  /**
   * Primary key, generated by Hibernate as a random UUID for new rows. The annotation overrides the
   * {@link AbstractEntity#getId()} accessor so {@link org.springframework.data.domain.Persistable}
   * resolves to this typed field rather than the erased base-class getter.
   */
  @Getter(onMethod_ = @__(@Override))
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  /**
   * The functional rank held in this position. Persisted as its enum name; the value must satisfy
   * the {@code chk_org_chart_scope} CHECK together with {@link #orgUnit}.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "position_type", nullable = false, length = 40)
  private OrgChartPositionType positionType;

  /**
   * The Staffel or Spezialkommando this position belongs to, or {@code null} for an area-leadership
   * position. Lazy because the assembly path resolves names/shorthands in bulk and most callers
   * never dereference it per row.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "org_unit_id")
  @ToString.Exclude
  private OrgUnit orgUnit;

  /**
   * The user holding this position. {@code null} only for a still-leaderless {@link
   * OrgChartPositionType#COMMAND_LEAD} Kommando (see the class-level "Kommando(gruppe)" note); the
   * {@code chk_org_chart_user} CHECK keeps it {@code NOT NULL} for every other rank. {@code ON
   * DELETE CASCADE} removes the position if the user row is hard-deleted.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_id")
  @ToString.Exclude
  private User user;

  /**
   * The Kommando's display name (Kommandogruppen-Name), e.g. {@code "Alpha"}. Only ever set on a
   * {@link OrgChartPositionType#COMMAND_LEAD} row — the {@code chk_org_chart_name} CHECK forces it
   * {@code null} for every other rank. {@code null} means the Kommando is unnamed; the UI then
   * shows a generic fallback label. Capped at 120 characters by the column definition.
   */
  @Column(name = "name", length = 120)
  private String name;

  /**
   * The position this one reports into within the same Staffel: a Kommandoleiter for a deputy, or
   * the Staffelleiter / a Kommandoleiter for an Ensign. {@code null} for every root position
   * (area-leadership ranks, Staffelleiter, Kommandoleiter, SK-Leiter).
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "parent_id")
  @ToString.Exclude
  private OrgChartPosition parent;

  /**
   * Stable display order within a sibling group (the four Kommandos of a Staffel, the coordinators
   * of the area leadership, …). Lower sorts first; ties fall back to {@code created_at}. Defaults
   * to {@code 0} so a freshly-created position lands at the front until reordered.
   */
  @Column(name = "sort_index", nullable = false)
  private int sortIndex;
}
