package de.greluc.krt.iri.basetool.backend.model.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.Instant;
import java.util.UUID;
import org.jetbrains.annotations.Nullable;

/**
 * Request DTO for {@code POST /api/v1/missions} and {@code POST /api/v1/missions/{id}/sub-missions}
 * — the create path for missions and sub-missions. Carries only the fields a caller is allowed to
 * set at create time; everything else is stamped server-side:
 *
 * <ul>
 *   <li>{@code id} / {@code version} / {@code coreVersion} / {@code scheduleVersion} / {@code
 *       flagsVersion}: generated by the persistence layer — the structural absence of these fields
 *       on this record makes it impossible for a caller to flip an existing mission's identity or
 *       short-circuit the optimistic-lock check.
 *   <li>{@code owner}: stamped from the authenticated caller in {@link
 *       de.greluc.krt.iri.basetool.backend.service.MissionService#createMission}.
 *   <li>{@code owningSquadron}: stamped from the owner's squadron (or the active squadron scope for
 *       admins) in {@code createMission}; sub-missions inherit from their parent in {@code
 *       addSubMission}.
 *   <li>{@code parent}: stamped from the path variable in {@code addSubMission} — never the body.
 *   <li>{@code managers} / participants / units / frequencies / inventory / refinery: have their
 *       own dedicated endpoints; not part of the create payload.
 *   <li>{@code actualStartTime} / {@code actualEndTime}: lifecycle-only fields, set via the {@code
 *       /schedule} patch endpoint or auto-stamped on status transition.
 * </ul>
 *
 * <p>This record is the security boundary for the create path (audit finding C-3): adding a field
 * here is an explicit decision to expose it to the API, while the absence of a field is a
 * structural guarantee that it cannot be smuggled in via JSON.
 */
public record CreateMissionRequest(
    @NotBlank @Size(max = 255) String name,
    @Nullable @Size(max = 10000) String description,
    @Nullable
        @Size(max = 2048)
        @Pattern(regexp = "^(https://.*)?$", message = "must start with https://")
        String calendarLink,
    @Nullable @Size(max = 64) String status,
    @Nullable Instant meetingTime,
    @Nullable Instant plannedStartTime,
    @Nullable Instant plannedEndTime,
    @Nullable Boolean isInternal,
    @Nullable UUID operationId) {}
