ALTER TABLE space_station
    ADD COLUMN is_available BOOLEAN,
    ADD COLUMN is_visible BOOLEAN,
    ADD COLUMN is_default BOOLEAN,
    ADD COLUMN is_monitored BOOLEAN,
    ADD COLUMN is_armistice BOOLEAN,
    ADD COLUMN is_landable BOOLEAN,
    ADD COLUMN is_decommissioned BOOLEAN,
    ADD COLUMN is_lagrange BOOLEAN,
    ADD COLUMN is_jump_point BOOLEAN,
    ADD COLUMN has_quantum_marker BOOLEAN,
    ADD COLUMN has_trade_terminal BOOLEAN,
    ADD COLUMN has_habitation BOOLEAN,
    ADD COLUMN has_refinery BOOLEAN,
    ADD COLUMN has_cargo_center BOOLEAN,
    ADD COLUMN has_clinic BOOLEAN,
    ADD COLUMN has_food BOOLEAN,
    ADD COLUMN has_shops BOOLEAN,
    ADD COLUMN has_refuel BOOLEAN,
    ADD COLUMN has_repair BOOLEAN,
    ADD COLUMN has_gravity BOOLEAN,
    ADD COLUMN has_loading_dock BOOLEAN,
    ADD COLUMN has_docking_port BOOLEAN,
    ADD COLUMN has_freight_elevator BOOLEAN,
    ADD COLUMN pad_types VARCHAR(255);

ALTER TABLE city
    ADD COLUMN is_available BOOLEAN,
    ADD COLUMN is_visible BOOLEAN,
    ADD COLUMN is_default BOOLEAN,
    ADD COLUMN is_monitored BOOLEAN,
    ADD COLUMN is_armistice BOOLEAN,
    ADD COLUMN is_landable BOOLEAN,
    ADD COLUMN is_decommissioned BOOLEAN,
    ADD COLUMN has_quantum_marker BOOLEAN,
    ADD COLUMN has_trade_terminal BOOLEAN,
    ADD COLUMN has_habitation BOOLEAN,
    ADD COLUMN has_refinery BOOLEAN,
    ADD COLUMN has_cargo_center BOOLEAN,
    ADD COLUMN has_clinic BOOLEAN,
    ADD COLUMN has_food BOOLEAN,
    ADD COLUMN has_shops BOOLEAN,
    ADD COLUMN has_refuel BOOLEAN,
    ADD COLUMN has_repair BOOLEAN,
    ADD COLUMN has_gravity BOOLEAN,
    ADD COLUMN has_loading_dock BOOLEAN,
    ADD COLUMN has_docking_port BOOLEAN,
    ADD COLUMN has_freight_elevator BOOLEAN,
    ADD COLUMN pad_types VARCHAR(255);

ALTER TABLE outpost
    ADD COLUMN is_available BOOLEAN,
    ADD COLUMN is_visible BOOLEAN,
    ADD COLUMN is_default BOOLEAN,
    ADD COLUMN is_monitored BOOLEAN,
    ADD COLUMN is_armistice BOOLEAN,
    ADD COLUMN is_landable BOOLEAN,
    ADD COLUMN is_decommissioned BOOLEAN,
    ADD COLUMN has_quantum_marker BOOLEAN,
    ADD COLUMN has_trade_terminal BOOLEAN,
    ADD COLUMN has_habitation BOOLEAN,
    ADD COLUMN has_refinery BOOLEAN,
    ADD COLUMN has_cargo_center BOOLEAN,
    ADD COLUMN has_clinic BOOLEAN,
    ADD COLUMN has_food BOOLEAN,
    ADD COLUMN has_shops BOOLEAN,
    ADD COLUMN has_refuel BOOLEAN,
    ADD COLUMN has_repair BOOLEAN,
    ADD COLUMN has_gravity BOOLEAN,
    ADD COLUMN has_loading_dock BOOLEAN,
    ADD COLUMN has_docking_port BOOLEAN,
    ADD COLUMN has_freight_elevator BOOLEAN,
    ADD COLUMN pad_types VARCHAR(255);

ALTER TABLE poi
    ADD COLUMN is_available BOOLEAN,
    ADD COLUMN is_visible BOOLEAN,
    ADD COLUMN is_default BOOLEAN,
    ADD COLUMN is_monitored BOOLEAN,
    ADD COLUMN is_armistice BOOLEAN,
    ADD COLUMN is_landable BOOLEAN,
    ADD COLUMN is_decommissioned BOOLEAN,
    ADD COLUMN has_quantum_marker BOOLEAN,
    ADD COLUMN has_trade_terminal BOOLEAN,
    ADD COLUMN has_habitation BOOLEAN,
    ADD COLUMN has_refinery BOOLEAN,
    ADD COLUMN has_cargo_center BOOLEAN,
    ADD COLUMN has_clinic BOOLEAN,
    ADD COLUMN has_food BOOLEAN,
    ADD COLUMN has_shops BOOLEAN,
    ADD COLUMN has_refuel BOOLEAN,
    ADD COLUMN has_repair BOOLEAN,
    ADD COLUMN has_gravity BOOLEAN,
    ADD COLUMN has_loading_dock BOOLEAN,
    ADD COLUMN has_docking_port BOOLEAN,
    ADD COLUMN has_freight_elevator BOOLEAN,
    ADD COLUMN pad_types VARCHAR(255);

ALTER TABLE planet
    ADD COLUMN is_available BOOLEAN,
    ADD COLUMN is_visible BOOLEAN,
    ADD COLUMN is_default BOOLEAN;

ALTER TABLE moon
    ADD COLUMN is_available BOOLEAN,
    ADD COLUMN is_visible BOOLEAN,
    ADD COLUMN is_default BOOLEAN;

ALTER TABLE terminal
    ADD COLUMN is_available BOOLEAN,
    ADD COLUMN is_visible BOOLEAN,
    ADD COLUMN is_jump_point BOOLEAN,
    ADD COLUMN has_loading_dock BOOLEAN,
    ADD COLUMN has_docking_port BOOLEAN,
    ADD COLUMN has_freight_elevator BOOLEAN;

