CREATE TABLE operation (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE mission ADD COLUMN operation_id UUID;
ALTER TABLE mission ADD CONSTRAINT fk_mission_operation FOREIGN KEY (operation_id) REFERENCES operation (id) ON DELETE SET NULL;
