package de.greluc.krt.iri.basetool.frontend.config;

import java.util.Optional;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.info.BuildProperties;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ModelAttribute;

/**
 * Cross-cutting advice that exposes the deployed application's version string to every Thymeleaf
 * model so the sidebar fragment can render a discreet build-version label under the language
 * switcher.
 *
 * <p>The value is sourced from Spring Boot's auto-configured {@link BuildProperties} bean, which in
 * turn reads {@code META-INF/build-info.properties} generated by the Gradle {@code bootBuildInfo}
 * task (enabled via {@code springBoot { buildInfo() }} in {@code frontend/build.gradle.kts}). The
 * dependency is injected as an {@link Optional} so test slices that do not load {@code
 * ProjectInfoAutoConfiguration} (e.g. {@code @WebMvcTest}) still wire the advice cleanly; in that
 * case the model attribute degrades to a literal {@code "dev"} marker instead of {@code null} so
 * the template never renders an empty version chip.
 */
@ControllerAdvice
@RequiredArgsConstructor
public class AppVersionAdvice {

  /**
   * Fallback string used whenever no {@link BuildProperties} bean is on the context (typical for
   * sliced web-MVC test runs that skip {@code ProjectInfoAutoConfiguration}). Kept short on purpose
   * so the sidebar chip stays unobtrusive in non-prod environments where the canonical Gradle
   * version isn't packaged.
   */
  static final String FALLBACK_VERSION = "dev";

  private final Optional<BuildProperties> buildProperties;

  /**
   * Resolves the version string for the {@code appVersion} Thymeleaf model attribute. Prefers the
   * value read from {@code META-INF/build-info.properties}; falls back to {@link #FALLBACK_VERSION}
   * when the auto-configured bean is absent or its {@code version} field is blank.
   *
   * @return non-{@code null} version string suitable for direct rendering in the sidebar fragment.
   */
  @ModelAttribute("appVersion")
  public String appVersion() {
    return buildProperties
        .map(BuildProperties::getVersion)
        .filter(v -> v != null && !v.isBlank())
        .orElse(FALLBACK_VERSION);
  }
}
