spring:
  datasource:
    url: jdbc:postgresql://db-backend:15432/krt_basetool
    #url: jdbc:postgresql://db-backend:15432/krt_basetool
    username: krt_user
    password: krt_password
  jpa:
    hibernate:
      ddl-auto: validate
      #ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak.iri-base.org/realms/iri}
