package de.greluc.krt.iri.basetool.backend.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * One filled functional-rank position in the Profit-Bereich org chart (see Flyway migration {@code
 * V136}). A row binds a {@link User} to an {@link OrgChartPositionType} within one of the three
 * scopes (area leadership / Staffel / Spezialkommando) and, for the squadron sub-tree, to a {@link
 * #parent} position.
 *
 * <p><b>Scope discriminator.</b> A {@code null} {@link #orgUnit} marks an area-leadership position
 * (Bereichsleitung); a non-null {@link #orgUnit} marks a Staffel- or SK-scoped position. The {@code
 * chk_org_chart_scope} CHECK constraint keeps {@code position_type} and the nullability of {@code
 * org_unit_id} consistent at the database layer.
 *
 * <p><b>Tree.</b> {@link #parent} is only set for {@link OrgChartPositionType#DEPUTY_COMMAND_LEAD}
 * (points at its Kommandoleiter) and {@link OrgChartPositionType#ENSIGN} (points at a
 * Kommandoleiter; {@code null} means the Ensign reports directly to the Staffelleiter). The
 * self-referencing FK is {@code ON DELETE CASCADE}, so deleting a Kommandoleiter row removes its
 * Stv. and the Ensigns reporting into it in one statement; the inline editor warns the admin about
 * those children before the delete.
 *
 * <p><b>Descriptive only.</b> Nothing here feeds authorization — the chart records who holds which
 * functional rank; permissions stay with the role model and the {@code org_unit_membership} flags.
 */
@Entity
@Table(name = "org_chart_position")
@Getter
@Setter
@NoArgsConstructor
@ToString(callSuper = true)
public class OrgChartPosition extends AbstractEntity<UUID> {

  /**
   * Primary key, generated by Hibernate as a random UUID for new rows. The annotation overrides the
   * {@link AbstractEntity#getId()} accessor so {@link org.springframework.data.domain.Persistable}
   * resolves to this typed field rather than the erased base-class getter.
   */
  @Getter(onMethod_ = @__(@Override))
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  /**
   * The functional rank held in this position. Persisted as its enum name; the value must satisfy
   * the {@code chk_org_chart_scope} CHECK together with {@link #orgUnit}.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "position_type", nullable = false, length = 40)
  private OrgChartPositionType positionType;

  /**
   * The Staffel or Spezialkommando this position belongs to, or {@code null} for an area-leadership
   * position. Lazy because the assembly path resolves names/shorthands in bulk and most callers
   * never dereference it per row.
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "org_unit_id")
  @ToString.Exclude
  private OrgUnit orgUnit;

  /**
   * The user holding this position. Never {@code null}; {@code ON DELETE CASCADE} removes the
   * position if the user row is hard-deleted.
   */
  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "user_id", nullable = false)
  @ToString.Exclude
  private User user;

  /**
   * The position this one reports into within the same Staffel: a Kommandoleiter for a deputy, or
   * the Staffelleiter / a Kommandoleiter for an Ensign. {@code null} for every root position
   * (area-leadership ranks, Staffelleiter, Kommandoleiter, SK-Leiter).
   */
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "parent_id")
  @ToString.Exclude
  private OrgChartPosition parent;

  /**
   * Stable display order within a sibling group (the four Kommandos of a Staffel, the coordinators
   * of the area leadership, …). Lower sorts first; ties fall back to {@code created_at}. Defaults
   * to {@code 0} so a freshly-created position lands at the front until reordered.
   */
  @Column(name = "sort_index", nullable = false)
  private int sortIndex;
}
