package de.greluc.krt.iri.basetool.backend.model;

import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorColumn;
import jakarta.persistence.DiscriminatorType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.persistence.Table;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Abstract base entity for the {@code org_unit} table — the shared parent of every tenant kind the
 * application recognises. Concrete subclasses use {@link OrgUnitKind} as a string discriminator on
 * the {@code kind} column and inherit the common columns ({@code id}, {@code name}, {@code
 * shorthand}, {@code description}, {@code active}, {@code is_promotion_enabled}) plus the audit
 * fields supplied by {@link AbstractEntity}.
 *
 * <p>Why a single-table inheritance hierarchy: the application has historically used one tenant
 * kind ({@code Squadron}) and is now growing a second ({@link SpecialCommand}, introduced by the
 * Spezialkommando R2.a slice — see {@code SPEZIALKOMMANDO_PLAN.md} §3). Both kinds share exactly
 * the same column shape (the {@code squadron} table was duplicated 1:1 into {@code org_unit} by
 * Flyway migration V94, gaining only the {@code kind} discriminator), so flattening the polymorphic
 * data into one table avoids the joined-strategy join cost without paying any structural price.
 * Subclasses that need their own columns can move to joined-strategy later via a dedicated
 * migration; nothing in the current shape needs subclass-specific columns.
 *
 * <p><b>Squadron is intentionally NOT in this hierarchy yet.</b> The legacy {@link Squadron} entity
 * still maps to the standalone {@code squadron} table during the R2.a soak window so the R1 schema
 * rollback path (drop the new tables, keep the legacy schema authoritative) stays viable. R2.b will
 * migrate {@code Squadron} to extend {@code OrgUnit}, switching its mapping to the {@code org_unit}
 * table and a {@code @DiscriminatorValue("SQUADRON")} marker. Until then, the {@code
 * kind='SQUADRON'} rows that V94 copied into {@code org_unit} are read-only ballast — readers of
 * {@code OrgUnit} (and any of its subclasses other than {@link SpecialCommand}) must avoid trying
 * to materialise them: {@link SpecialCommand}'s repository filters on the discriminator
 * automatically, and {@code OrgUnitMembership} stores {@code org_unit_id} as a plain UUID instead
 * of a JPA relation to {@code OrgUnit} so Hibernate cannot raise a {@code WrongClassException} on
 * a {@code SQUADRON}-discriminated row that has no Java subclass.
 *
 * <p>Promotion-feature invariant: {@link #isPromotionEnabled} stays on this superclass so the
 * existing {@code SquadronScopeService.isPromotionFeatureEnabledForCurrentScope} contract carries
 * over unchanged once {@code Squadron} moves into the hierarchy in R2.b. The database CHECK
 * constraint {@code chk_org_unit_promotion_only_squadron} (V94) enforces that {@code
 * is_promotion_enabled} is false for every {@code SPECIAL_COMMAND} row, so a careless setter call
 * on a {@link SpecialCommand} instance surfaces as a constraint violation at flush time rather than
 * silently exposing the promotion menu to SK members.
 */
@Entity
@Table(name = "org_unit")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "kind", discriminatorType = DiscriminatorType.STRING, length = 32)
@Getter
@Setter
@ToString
@NoArgsConstructor
public abstract class OrgUnit extends AbstractEntity<UUID> {

  /**
   * Primary key, generated by Hibernate as a random UUID for new rows. The annotation also
   * overrides the {@link AbstractEntity#getId()} getter so {@link
   * org.springframework.data.domain.Persistable#getId()} resolves to the typed UUID field rather
   * than the erased base-class accessor.
   */
  @Getter(onMethod_ = @__(@Override))
  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  private UUID id;

  /**
   * Human-readable display name. Unique across all kinds (so a Spezialkommando cannot be named
   * "IRIDIUM" while the IRIDIUM squadron also exists), matching the {@code UNIQUE} constraint
   * inherited from the original {@code squadron} schema and preserved by V94.
   */
  @Column(unique = true, nullable = false)
  private String name;

  /**
   * Short identifier (3-5 letters) used in badges, chips, and audit logs. Unique across all kinds
   * for the same reasons as {@link #name}.
   */
  @Column(unique = true, nullable = false)
  private String shorthand;

  /** Free-text description shown on admin pages. May be {@code null} for newly-created rows. */
  @Column(columnDefinition = "TEXT")
  private String description;

  /**
   * Soft-delete flag. {@code false} hides the org unit from list views without deleting any data.
   * Defaults to {@code true} so a freshly-constructed entity goes straight into active state — the
   * existing {@code SquadronService.deleteSquadron} flow flips this rather than emitting a DELETE,
   * and {@link SpecialCommand} mirrors that behaviour.
   */
  @Column(nullable = false)
  private boolean active = true;

  /**
   * Per-org-unit feature flag deciding whether the promotion subsystem (topics, categories,
   * level-contents, rank-requirements, member-evaluations) is exposed to non-admin members of this
   * org unit. Default {@code true} so existing squadrons continue to expose the menu after the V86
   * migration that introduced the column. The V94 CHECK constraint {@code
   * chk_org_unit_promotion_only_squadron} forces this to {@code false} on every {@code
   * SPECIAL_COMMAND} row regardless of what the application tries to write, so admin tooling cannot
   * accidentally enable promotion on a Spezialkommando.
   */
  @Column(name = "is_promotion_enabled", nullable = false)
  private boolean isPromotionEnabled = true;

  /**
   * Returns the concrete {@link OrgUnitKind} this row represents. Each concrete subclass overrides
   * this with a constant value matching its {@code @DiscriminatorValue}. The discriminator column
   * itself is read-only at the JPA layer (Hibernate manages it via the inheritance metadata), so
   * application code reaches for this method instead of trying to read the {@code kind} column
   * directly.
   *
   * @return the discriminator kind for this concrete row, never {@code null}.
   */
  public abstract OrgUnitKind getKind();
}
